version: "3.8"

services:
  task-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - resilient-tasks-network

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - resilient-tasks-network

networks:
  resilient-tasks-network:
    driver: bridge

volumes:
  mongo_data:
